// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package precompiledseccomp

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"
)

const libraryHeader = `// Copyright 2023 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by precompiledseccomp. DO NOT EDIT.

`

// WriteLibrary writes a Go source file in package pkgName to path. The file
// embeds programs and defines GetPrecompiled, ListPrecompiled and
// PrecompilationDisabledAtBuildTime.
func WriteLibrary(path, pkgName string, programs []Program, disabledAtBuildTime bool) error {
	programs = slices.Clone(programs)
	slices.SortFunc(programs, func(a, b Program) int {
		return strings.Compare(a.Name, b.Name)
	})
	for i := 1; i < len(programs); i++ {
		if programs[i].Name == programs[i-1].Name {
			return fmt.Errorf("duplicate program name %q", programs[i].Name)
		}
	}

	file, err := os.Create(path)
	if err != nil {
		return err
	}
	w := bufio.NewWriter(file)
	fmt.Fprint(w, libraryHeader)
	fmt.Fprintf(w, "package %s\n\n", pkgName)
	fmt.Fprint(w, "import (\n\t\"gvisor.dev/gvisor/pkg/seccomp/precompiledseccomp\"\n)\n\n")
	fmt.Fprint(w, "var (\n")
	fmt.Fprint(w, "\t// precompiledProgramNames is the sorted list of all precompiled program\n")
	fmt.Fprint(w, "\t// names. It is populated at generation time and used by `ListPrecompiled`.\n")
	fmt.Fprint(w, "\tprecompiledProgramNames = []string{\n")
	for _, program := range programs {
		fmt.Fprintf(w, "\t\t%q,\n", program.Name)
	}
	fmt.Fprint(w, "\t}\n)\n\n")
	fmt.Fprint(w, "// PrecompilationDisabledAtBuildTime is a constant that is used to\n")
	fmt.Fprint(w, "// indicate that precompilation was disabled at build time.\n")
	fmt.Fprintf(w, "const PrecompilationDisabledAtBuildTime = %t\n\n", disabledAtBuildTime)
	fmt.Fprint(w, "// GetPrecompiled returns the precompiled program for the given name,\n")
	fmt.Fprint(w, "// and whether that program name exists.\n")
	fmt.Fprint(w, "func GetPrecompiled(programName string) (precompiledseccomp.Program, bool) {\n")
	fmt.Fprint(w, "\tswitch programName {\n")
	for _, program := range programs {
		fmt.Fprint(w, program.SwitchCase("precompiledseccomp"))
	}
	fmt.Fprint(w, "\t}\n\treturn precompiledseccomp.Program{}, false\n}\n\n")
	fmt.Fprint(w, "// ListPrecompiled returns a list of all registered program names.\n")
	fmt.Fprint(w, "func ListPrecompiled() []string {\n")
	fmt.Fprint(w, "\treturn append([]string(nil), precompiledProgramNames...)\n}\n")
	if err := w.Flush(); err != nil {
		file.Close()
		return err
	}
	return file.Close()
}
